# The Docker image that will be used to build your app
image: rocker/tidyverse:latest

variables:
  CHECK_DIR: "$CI_PROJECT_DIR/ci/logs"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs/$CI_PROJECT_NAME.Rcheck"

test:
  script:
    - mkdir -p $R_LIBS_USER $BUILD_LOGS_DIR
    - R -e 'devtools::install_dev_deps(dep = T)'
    - R -e 'check_result <- devtools::check(check_dir = Sys.getenv("CHECK_DIR")); check_result; if (check_result$status == 1) stop()'

  artifacts:
    paths:
      - $CHECK_DIR
  rules:
  # This ensures that only pushes to the default branch will trigger
  # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  script:
    - Rscript -e 'devtools::install()'
    - Rscript -e 'pkgdown::build_site()'
    - mv docs public

  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
